version: '3.7'
name: role-api
services:
  postgres:
    env_file: .env
    container_name: rolebase
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT:-5440}:5432"
    restart: unless-stopped

volumes:
  postgres: